### ISSUE TITLE
Invalid literal for int() with base 10

### ISSUE THREAD

**Issue by LawrenceWlt** [mozilla/ichnaea#1143]
Running the command `docker run -it --rm --env-file env.txt     mozilla/location:2.1.0 alembic stamp base` results to the following error;

Running Alembic
Traceback (most recent call last):
  File "/app/bin/alembic", line 11, in <module>
    load_entry_point('alembic==0.9.2', 'console_scripts', 'alembic')()
  File "/app/lib/python3.6/site-packages/alembic/config.py", line 479, in main
    CommandLine(prog=prog).main(argv=argv)
  File "/app/lib/python3.6/site-packages/alembic/config.py", line 473, in main
    self.run_cmd(cfg, options)
  File "/app/lib/python3.6/site-packages/alembic/config.py", line 456, in run_cmd
    **dict((k, getattr(options, k, None)) for k in kwarg)
  File "/app/lib/python3.6/site-packages/alembic/command.py", line 496, in stamp
    script.run_env()
  File "/app/lib/python3.6/site-packages/alembic/script/base.py", line 421, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/app/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/app/lib/python3.6/site-packages/alembic/util/compat.py", line 64, in load_module_py
    module_id, path).load_module(module_id)
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "ichnaea/alembic/env.py", line 19, in <module>
    run_migrations_online()
  File "ichnaea/alembic/env.py", line 10, in run_migrations_online
    db = configure_db('ddl')
  File "/app/ichnaea/db.py", line 68, in configure_db
    return Database(uri, pool=pool, transport=transport)
  File "/app/ichnaea/db.py", line 158, in __init__
    self.engine = create_engine(uri, **options)
  File "/app/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
    return strategy.create(*args, **kwargs)
  File "/app/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 50, in create
    u = url.make_url(name_or_url)
  File "/app/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 194, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/app/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 240, in _parse_rfc1738_args
    return URL(name, **components)
  File "/app/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 60, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: '3306:3306'

**Comment by LawrenceWlt** [comment]
My env.txt is as follows;
```
DB_HOST=localhost:3306
DB_USER=root
DB_PASSWORD=********
GEOIP_PATH=/app/geoip/GeoLite2-City.mmdb
REDIS_HOST=127.0.0.1:6379
```

**Comment by jwhitlock** [comment]
@LawrenceWlt, thanks for the report. 

First, a warning. The [deployment doc](https://ichnaea.readthedocs.io/en/latest/deploy.html) is out of date, and tag `2.1.0` is three years old. The current code is in the `latest` tag, but the documentation hasn't been updated.

Thanks for posting your `env.txt`. The `DB_HOST` should *not* have a port:

```
DB_HOST=localhost
```

The next error will be:

```
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (2003, "Can't connect to MySQL server on 'localhost' ([Errno 99] Cannot assign requested address)")
```

"localhost" is the Docker instance, and doesn't have a MySQL server. If you are trying to connect to a MySQL instance on your "host" system (your desktop or laptop), then you'll need some more docker magic. See [From inside of a Docker container, how do I connect to the localhost of the machine?](https://stackoverflow.com/q/24319662/10612) as a starting point.

**Comment by jwhitlock** [comment]
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1628047 to update deployment documentation.

**Comment by jwhitlock** [comment]
@LawrenceWlt we still have work to do on [bug 1628047](https://bugzilla.mozilla.org/show_bug.cgi?id=1628047), but I think my answer should get you unstuck. If you continue to have issues, feel free to comment, re-open, or open a new issue.
