### ISSUE TITLE
Make development environment compatible with Apple Silicon M1

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#1636]
Apple computers released in 2020 and later come with the M1 chip, which is detected as `linux/arm64/v8` by [Docker Desktop for Apple Silicon](https://docs.docker.com/docker-for-mac/apple-silicon/). Previous computers were detected as `linux/amd64`. The application image is unable to build on a M1 laptop, because MySQL does not distribute `arm64` packages, only `amd64` and `i386`. There may be further issues after this is solved.

Some possibilities:

* Run under emulation, with ``--platform linux/amd64`` and other options
* Switch to [MariaDB](https://mariadb.com/database-topics/mariadb-vs-mysql/) for client libraries, which should be compatible
* Switch from MySQL to MariaDB for the database server as well.

We intend to continue running MySQL 5.7 in production, and want to avoid issues due to further mismatches between development and deployments.

**Comment by jwhitlock** [comment]
I've read and experimented a bit, and got to working code on my M1-based laptop.

The Oracle MySQL team [supports MySQL server 8.0](https://hub.docker.com/r/mysql/mysql-server/) with x86 and arm64 releases. I don't expect them to ever support arm64 for 5.7.

I haven't researched why, but the official Debian package repositories stop at MySQL 5.5, so we use a repository hosted by mysql.com. The MySQL Debian repo does not have arm64 packages for [MySQL 5.7](https://repo.mysql.com/apt/debian/dists/buster/mysql-5.7/) or [MySQL 8.0](https://repo.mysql.com/apt/debian/dists/buster/mysql-8.0/). There may be something that changed recently, since there is a sid (unstable) build of [MySQL server 8.0.23-3+b1](https://packages.debian.org/sid/mysql-server-8.0) for arm64 and other architectures.

I don't think waiting for upstream support will be an effective option. It may be possible to run a MySQL 8.0 server image under arm64 locally, but that should be part of a production server update from 5.7 to 8.0, and doesn't address the client libraries.

I tried running the MySQL 5.7 docker image with emulation, but it failed to load. It is possible that I could get it working with more effort, or by turning on some experimental flags. I'm not excited by the [docker notes](https://docs.docker.com/docker-for-mac/apple-silicon/), which mention crashes, missing features, and “best effort” for container emulation.

I was able to get the Ichnaea images to build as arm64 with MariaDB libraries, talking to a MariaDB 10.5 database (arm64 image). The application runs and tests pass. This may be the most effective M1 development combination.

I'm going to see if the MariaDB client libraries work for both arm64 and amd64 architectures for my initial PR. If they do, then the same libraries would work for local development and production, and remove a source of "works for me" errors.

**Comment by jwhitlock** [comment]
I mentioned emulation failed to load MySQL 5.7.  There was a Docker update (Docker Desktop 3.5.2), so I tried it again.

If I add `platform: linux/amd64` to the MySQL 5.7 container definition in ``docker-compose.yml``, then I can get ``make build`` to work, but starting the container fails with this log:

```
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x524da0, 0x9)
	/usr/local/go/src/runtime/panic.go:527 +0x90
runtime.newosproc(0xc82002a000, 0xc820039fc0)
	/usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
runtime.newm(0x555ce8, 0x0)
	/usr/local/go/src/runtime/proc1.go:1105 +0x130
runtime.main.func1()
	/usr/local/go/src/runtime/proc.go:48 +0x2c
runtime.systemstack(0x5c4300)
	/usr/local/go/src/runtime/asm_amd64.s:262 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc820024770 sp=0xc820024768
runtime.main()
	/usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc8200247c0 sp=0xc820024770
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc8200247c8 sp=0xc8200247c0
```

**Comment by jwhitlock** [comment]
The Moby Buildkit builder allows creating multiple platform Docker images with the same tag. This is accessible with [docker buildx](https://docs.docker.com/buildx/working-with-buildx/). It would be useful for this bug to ship ``linux/arm64`` Docker images to go along with the ``linux/amd64`` images.

**Comment by jwhitlock** [comment]
In PR #1762, I was successful at getting a CircleCI machine executor to run `docker buildx`, cross-compile `linux/arm64` and `linux/amd64`, and upload a multi-platform docker manifest. The Jenkins job saw the new image and was able to successfully deploy it to stage.  It also took 35 minutes to build, versus the 5 minutes for a `linux/amd64` image built in a Docker container.

CircleCI could make this easy by providing remote Docker machines running arm64. Without that, a working solution may be a multi-step build, where a machine executor builds each platform, and a final step uploads the combined manifest. This may be possible today, with a few hard parts:
* Building with `docker build` rather than `docker-compose build` via `make build`
* Ensuring the right platform setting is used in the build, via ``--platform``
* Ensuring that experimental features are enabled, so [docker manifest](https://docs.docker.com/engine/reference/commandline/manifest/) is available
* Getting the per-platform manifests to the final job, possibly via the [workspace](https://circleci.com/docs/2.0/workflows/#using-workspaces-to-share-data-among-jobs)

The only benefit is that someone running `linux/arm64` (such as a Docker Desktop user on an M1 MacBook) can download the image and run Docker. Currently, it is not much more difficult (for me at least) to build your own, and then you are ready for software development or local testing. We're not planning to deploy on arm64, and compatible code changes have not yet been an issue. So, I'm going to pause on efforts to build and test on arm64 in CircleCI.
