### ISSUE TITLE
test_locate_v1.test_blue_seen fails occasionally

### ISSUE THREAD

**Issue by jwhitlock** [mozilla/ichnaea#921]
The test ``test_blue_seen`` in ``ichnaea/api/locate/tests/test_locate_v1.py`` fails occasionally, such as a recent failure:

```
___________________________ TestView.test_blue_seen ____________________________
Traceback (most recent call last):
  File "/app/ichnaea/api/locate/tests/test_locate_v1.py", line 176, in test_blue_seen
    self.check_queue(data_queues, 0)
  File "/app/ichnaea/api/locate/tests/base.py", line 210, in check_queue
    assert data_queues["update_incoming"].size() == num
AssertionError
```

As [willkg says](https://github.com/mozilla/ichnaea/pull/920#issuecomment-534136454), it's weird that the assertion error shows like that and doesn't show the pytest fancy assertion stuff.

Here's the code:

https://github.com/mozilla/ichnaea/blob/7ee9de14a2b44456adf71b3d3113f5cbdf851bdf/ichnaea/api/locate/tests/test_locate_v1.py#L168-L176

The "v1" API is the current locate API, "v0" is the deprecated API. ``BlueShardFactory`` has some randomness for the MAC address, but the lat and long are constant:

https://github.com/mozilla/ichnaea/blob/5b020c4bd41246f3cefb98949a9555e598fe7e45/ichnaea/tests/factories.py#L143-L157

The frequency of failures may give some information, as well as if it is always this test that fails.

**Comment by jwhitlock** [comment]
It failed today on [build 1703](https://circleci.com/gh/mozilla/ichnaea/1703), for the PR. It failed 4 days ago in [build 1689](https://circleci.com/gh/mozilla/ichnaea/1689), merging a PR to master.  That's 14 builds between failures, so if it was pure randomness, I'd expect to have seen more failures in the previous month. This makes it more likely to be a recent requirements update 😓

**Comment by jwhitlock** [comment]
Recent failures:

* Wed Oct 2 9:13 AM: [Build 1756](https://circleci.com/gh/mozilla/ichnaea/1756)
* Wed Oct 9 8:22 AM: [Build 1783](https://circleci.com/gh/mozilla/ichnaea/1783)

Weekly is still super annoying. I'm starting with investigating why the pytest enchanced assert isn't being used.

**Comment by jwhitlock** [comment]
With PR #950 merged, we should get pytest enhanced ``assert`` the next this fails.

**Comment by jwhitlock** [comment]
On Monday Oct 21, [build 1823](https://circleci.com/gh/mozilla/ichnaea/1823) with a traceback:

```
___________________________ TestView.test_blue_seen ____________________________
Traceback (most recent call last):
  File "/app/ichnaea/api/locate/tests/test_locate_v1.py", line 182, in test_blue_seen
    self.check_queue(data_queues, 0)
  File "/app/ichnaea/api/locate/tests/base.py", line 208, in check_queue
    assert data_queues["update_incoming"].size() == num
AssertionError: assert 1 == 0
 +  where 1 = <bound method DataQueue.size of <ichnaea.queue.DataQueue object at 0x7fb068d55890>>()
 +    where <bound method DataQueue.size of <ichnaea.queue.DataQueue object at 0x7fb068d55890>> = <ichnaea.queue.DataQueue object at 0x7fb068d55890>.size
```

So, we know the queue was empty at the start of the test, and there was exactly one item at the end of the test.

**Comment by willkg** [comment]
Here's some wondering out loud without looking at the code so I don't forget what I was thinking when I read this comment. I wonder if the tests wipe redis state before each test. I wonder if there are race conditions where the celery task goes to run, but nothing is there. Maybe we need a pause after inserting things into data queues and before running celery things?

**Comment by jwhitlock** [comment]
My assumption is that this test is checking that reports are not added to the ``update_incoming`` queue if there is no new data to process (all the radios are already in the database and up-to-date). The test above ``test_blue`` shows the expected report in ``update_incoming`` for new data, and may be a guide for how to peek at the queued report for ``test_blue_seen``.

I was hoping there was another test that also tested this functionality, maybe for cell or wifi stations, but no luck. This appears to be the only one.

Here's the fixtures:

* ``app``: A webtest-wrapped instance of the WSGI app, runs ``shutdown_worker`` at end of tests. Takes a ``redis`` fixture that runs ``flushdb()``
* ``data_queues``: Returns just the ``update_incoming`` queue. Tested to be empty at start of test.
* ``session``: A database session that runs in a transaction, and rolls back at the end of the test.

In the past, I've seen issues with age tests that fail around midnight, month transitions, etc. Here's the time of day of failing tests from my clock (UTC-5):

* [build 1703](https://circleci.com/gh/mozilla/ichnaea/1703) - 09:48
* [build 1689](https://circleci.com/gh/mozilla/ichnaea/1689) - 12:05
* [build 1756](https://circleci.com/gh/mozilla/ichnaea/1756) - 09:13
* [build 1783](https://circleci.com/gh/mozilla/ichnaea/1783) - 08:22
* [build 1823](https://circleci.com/gh/mozilla/ichnaea/1823) - 13:44

So much for past testing experience 😬

I think the next step is:
* Confirm the queue is empty at the end of the DB flush
* If there is a report in the queue, ensure the report appears in the test failure output, and maybe dump database state as well.

If this is too annoying, I could also use something like ``pytest-rerunfailures`` of something else from https://docs.pytest.org/en/latest/flaky.html so that we can get tests to pass automatically. For now, I'm using this test to try to understand the data pipeline better.

**Comment by jwhitlock** [comment]
This continues to happen, and I got one in my dev environment!

Here are the recent failures. It shows that the report is related to the query.
* [build 1833](https://circleci.com/gh/mozilla/ichnaea/1833): 
    ```
    Query:
    {'bluetoothBeacons': [
        {'macAddress': 'a82067491500'},
        {'macAddress': 'a82070169727'}]}
    Report:
    [{'api_key': 'test', 'source': 'query', 'report': {
         'bluetoothBeacons': [
             {'macAddress': 'a82067491500'},
             {'macAddress': 'a82070169727'}],
         'fallbacks': {'ipf': True, 'lacf': True},
         'position': {'latitude': 51.50001, 'longitude': -0.1,
                      'accuracy': 10.0, 'source': 'query'}}}]
    ```
* [build 1903](https://circleci.com/gh/mozilla/ichnaea/1903):
    ```
    Query:
    {'bluetoothBeacons': [
        {'macAddress': 'a82076784926'},
        {'macAddress': 'a82018842400'}]}
    Report:
    [{'api_key': 'test', 'source': 'query', 'report': {
        'bluetoothBeacons': [
            {'macAddress': 'a82076784926'},
            {'macAddress': 'a82018842400'}],
        'fallbacks': {'ipf': True, 'lacf': True},
        'position': {'latitude': 51.50001, 'longitude': -0.1,
                     'accuracy': 10.0, 'source': 'query'}}}]
    ```
* [build 1912](https://circleci.com/gh/mozilla/ichnaea/1912):
   ```
   Query:
   {'bluetoothBeacons': [
       {'macAddress': 'a82040017600'},
       {'macAddress': 'a82017146546'}]}
   Report:
   [{'api_key': 'test', 'source': 'query', 'report': {
       'bluetoothBeacons': [
           {'macAddress': 'a82040017600'},
           {'macAddress': 'a82017146546'}],
        'fallbacks': {'ipf': True, 'lacf': True},
        'position': {'latitude': 51.50001, 'longitude': -0.1,
                     'accuracy': 10.0, 'source': 'query'}}}]
   ```

In my dev environment, I have SQLAlchemy logging on, so I have a richer log than tests normally have:

```
Traceback (most recent call last):
  File "/app/ichnaea/api/locate/tests/test_locate_v1.py", line 193, in test_blue_seen
    ).format(query, items)
  File "/usr/local/lib/python3.7/site-packages/_pytest/outcomes.py", line 128, in fail
    raise Failed(msg=msg, pytrace=pytrace)
Failed: Query added a report to the update_incoming queue.
Query:
{'bluetoothBeacons': [{'macAddress': 'a82054935406'}, {'macAddress': 'a82026440500'}]}
Report:
[{'api_key': 'test', 'source': 'query', 'report': {'bluetoothBeacons': [{'macAddress': 'a82054935406'}, {'macAddress': 'a82026440500'}], 'fallbacks': {'ipf': True, 'lacf': True}, 'position': {'latitude': 51.50001, 'longitude': -0.1, 'accuracy': 10.0, 'source': 'query'}}}]
----------------------------------------------------------------------------------------------- Captured stderr setup -----------------------------------------------------------------------------------------------
2019-12-05 15:16:31,434 INFO  [sqlalchemy.engine.base.Engine] - BEGIN (implicit)
----------------------------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------------------------------
2019-12-05 15:16:31,438 INFO  [sqlalchemy.engine.base.Engine] - INSERT INTO blue_shard_5 (max_lat, min_lat, max_lon, min_lon, lat, lon, created, modified, radius, region, samples, source, weight, last_seen, block_first, block_last, block_count, mac) VALUES (%(max_lat)s, %(min_lat)s, %(max_lon)s, %(min_lon)s, %(lat)s, %(lon)s, %(created)s, %(modified)s, %(radius)s, %(region)s, %(samples)s, %(source)s, %(weight)s, %(last_seen)s, %(block_first)s, %(block_last)s, %(block_count)s, %(mac)s)
2019-12-05 15:16:31,438 INFO  [sqlalchemy.engine.base.Engine] - {'max_lat': None, 'min_lat': None, 'max_lon': None, 'min_lon': None, 'lat': 51.5, 'lon': -0.1, 'created': datetime.datetime(2019, 12, 5, 15, 16, 19), 'modified': datetime.datetime(2019, 12, 5, 15, 16, 19), 'radius': 5, 'region': 'GB', 'samples': 1, 'source': 3, 'weight': 1.0, 'last_seen': datetime.date(2019, 12, 5), 'block_first': None, 'block_last': None, 'block_count': None, 'mac': b'\xa8 T\x93T\x06'}
2019-12-05 15:16:31,440 INFO  [sqlalchemy.engine.base.Engine] - INSERT INTO blue_shard_2 (max_lat, min_lat, max_lon, min_lon, lat, lon, created, modified, radius, region, samples, source, weight, last_seen, block_first, block_last, block_count, mac) VALUES (%(max_lat)s, %(min_lat)s, %(max_lon)s, %(min_lon)s, %(lat)s, %(lon)s, %(created)s, %(modified)s, %(radius)s, %(region)s, %(samples)s, %(source)s, %(weight)s, %(last_seen)s, %(block_first)s, %(block_last)s, %(block_count)s, %(mac)s)
2019-12-05 15:16:31,440 INFO  [sqlalchemy.engine.base.Engine] - {'max_lat': None, 'min_lat': None, 'max_lon': None, 'min_lon': None, 'lat': 51.50002, 'lon': -0.1, 'created': datetime.datetime(2019, 12, 5, 15, 16, 19), 'modified': datetime.datetime(2019, 12, 5, 15, 16, 19), 'radius': 5, 'region': 'GB', 'samples': 1, 'source': 3, 'weight': 1.0, 'last_seen': datetime.date(2019, 12, 5), 'block_first': None, 'block_last': None, 'block_count': None, 'mac': b'\xa8 &D\x05\x00'}
2019-12-05 15:16:31,443 INFO  [sqlalchemy.engine.base.Engine] - SELECT api_key.valid_key, api_key.maxreq, api_key.allow_fallback, api_key.allow_locate, api_key.allow_region, api_key.fallback_name, api_key.fallback_schema, api_key.fallback_url, api_key.fallback_ratelimit, api_key.fallback_ratelimit_interval, api_key.fallback_cache_expire, api_key.store_sample_submit, api_key.store_sample_locate 
FROM api_key 
WHERE api_key.valid_key = %(valid_key_1)s
2019-12-05 15:16:31,443 INFO  [sqlalchemy.engine.base.Engine] - {'valid_key_1': 'test'}
2019-12-05 15:16:31,444 DEBUG [sqlalchemy.engine.base.Engine] - Col ('valid_key', 'maxreq', 'allow_fallback', 'allow_locate', 'allow_region', 'fallback_name', 'fallback_schema', 'fallback_url', 'fallback_ratelimit', 'fallback_ratelimit_interval', 'fallback_cache_expire', 'store_sample_submit', 'store_sample_locate')
2019-12-05 15:16:31,445 DEBUG [sqlalchemy.engine.base.Engine] - Row ('test', 0, 0, 1, 1, 'fall', None, 'http://127.0.0.1:9/?api', 10, 60, 60, 100, 100)
2019-12-05 15:16:31,445 INFO  [markus] - METRICS|2019-12-05 15:16:31|incr|locate.request|1|#path:v1.geolocate,key:test
2019-12-05 15:16:31,446 INFO  [markus] - METRICS|2019-12-05 15:16:31|incr|locate.query|1|#key:test,region:none,geoip:false,blue:many,cell:none,wifi:none
2019-12-05 15:16:31,447 INFO  [sqlalchemy.engine.base.Engine] - SELECT blue_shard_5.mac, blue_shard_5.lat, blue_shard_5.lon, blue_shard_5.radius, blue_shard_5.region, blue_shard_5.samples, blue_shard_5.created, blue_shard_5.modified, blue_shard_5.last_seen, blue_shard_5.block_last, blue_shard_5.block_count 
FROM blue_shard_5 
WHERE blue_shard_5.lat IS NOT NULL AND blue_shard_5.lon IS NOT NULL AND blue_shard_5.mac IN (%(mac_1)s)
2019-12-05 15:16:31,447 INFO  [sqlalchemy.engine.base.Engine] - {'mac_1': b'\xa8 T\x93T\x06'}
2019-12-05 15:16:31,448 DEBUG [sqlalchemy.engine.base.Engine] - Col ('mac', 'lat', 'lon', 'radius', 'region', 'samples', 'created', 'modified', 'last_seen', 'block_last', 'block_count')
2019-12-05 15:16:31,449 DEBUG [sqlalchemy.engine.base.Engine] - Row (b'\xa8 T\x93T\x06', 51.5, -0.1, 5, 'GB', 1, datetime.datetime(2019, 12, 5, 15, 16, 19), datetime.datetime(2019, 12, 5, 15, 16, 19), datetime.date(2019, 12, 5), None, None)
2019-12-05 15:16:31,450 INFO  [sqlalchemy.engine.base.Engine] - SELECT blue_shard_2.mac, blue_shard_2.lat, blue_shard_2.lon, blue_shard_2.radius, blue_shard_2.region, blue_shard_2.samples, blue_shard_2.created, blue_shard_2.modified, blue_shard_2.last_seen, blue_shard_2.block_last, blue_shard_2.block_count 
FROM blue_shard_2 
WHERE blue_shard_2.lat IS NOT NULL AND blue_shard_2.lon IS NOT NULL AND blue_shard_2.mac IN (%(mac_1)s)
2019-12-05 15:16:31,450 INFO  [sqlalchemy.engine.base.Engine] - {'mac_1': b'\xa8 &D\x05\x00'}
2019-12-05 15:16:31,451 DEBUG [sqlalchemy.engine.base.Engine] - Col ('mac', 'lat', 'lon', 'radius', 'region', 'samples', 'created', 'modified', 'last_seen', 'block_last', 'block_count')
2019-12-05 15:16:31,451 DEBUG [sqlalchemy.engine.base.Engine] - Row (b'\xa8 &D\x05\x00', 51.50002, -0.1, 5, 'GB', 1, datetime.datetime(2019, 12, 5, 15, 16, 19), datetime.datetime(2019, 12, 5, 15, 16, 19), datetime.date(2019, 12, 5), None, None)
2019-12-05 15:16:31,453 INFO  [markus] - METRICS|2019-12-05 15:16:31|incr|locate.source|1|#key:test,region:none,source:internal,accuracy:high,status:hit
2019-12-05 15:16:31,454 INFO  [markus] - METRICS|2019-12-05 15:16:31|incr|locate.result|1|#key:test,region:none,fallback_allowed:false,accuracy:high,status:hit,source:internal
2019-12-05 15:16:31,454 INFO  [sqlalchemy.engine.base.Engine] - ROLLBACK
2019-12-05 15:16:31,457 INFO  [markus] - METRICS|2019-12-05 15:16:31|timing|request.timing|15|#path:v1.geolocate,method:post
2019-12-05 15:16:31,457 INFO  [markus] - METRICS|2019-12-05 15:16:31|incr|request|1|#path:v1.geolocate,method:post,status:200
```

OK, this is a lot of data, but the take-aways are:

* The location is based on the BlueTooth locations, not the IP-based fallback
* For some reason, these dictionaries are equal most of the time, but unequal for these cases:

https://github.com/mozilla/ichnaea/blob/0db0c106d2fdbc11dc076763ba165871960c7c94/ichnaea/api/locate/internal.py#L58-L67

I'm working on something else at the moment, but I'll return to explore more when I'm done.

**Comment by jwhitlock** [comment]
The failure happens if the hexadecimal MAC ends in two '00' digits, the binary string ends in a null (`\x00`). For example, `a82025820500` in hex is `b'\xa8 %\x82\x05\x00'`. This is dropped from the MAC by the time it gets to the `result_network`, and retained in the `query.networks()`, and fails to match:

```python
b'\xa8 %\x82\x05' != b'\xa8 %\x82\x05\x00'
```

Since the strings don't match, the station with the truncated MAC is detected as a new station.

The last digit would randomly be `00` 1 in 256 times, and two are picked for the test, so we'd expect 1 out of 128 test runs to fail.

**Comment by jwhitlock** [comment]
This is an issue with storing null-terminated byte strings in a numpy array, see https://github.com/numpy/numpy/issues/8089. It doesn't look like it will be fixed upstream, so we'll need a local fix.

**Comment by willkg** [comment]
Is this a problem both in the tests and also in stage/prod?

**Comment by jwhitlock** [comment]
Sorry, closed before answering...

> Is this a problem both in the tests and also in stage/prod?

Yes, this is a problem in stage and production deployments as well.

My understanding is that this would tend to add more location query reports for further processing than are needed. If any of the WiFi stations ended in `00`, then the entire location query would be sent as potentially including a new station. There may be a variant for cell stations, such as ones with a cell ID of 0. Our data pipeline is under a lot of stress, so adding more reports than are needed is bad.

Any "new" station detected this way would cause the whole location query to be queued as a new report. I'm not sure if the last two hex digits of MAC IDs are random, so I'm not sure how to estimate how many times this bug would trigger a false new report.

I'm not sure what happens when it gets to ``StationUpdater``. I think that data conversions would add back the trailing `00` to station IDs, so it would get through processing as a "no change" action.

I was unable to see if this was an issue in the 1.5.x deployments (maybe it always worked in a previous numpy).

**Comment by hannosch** [comment]
A cid value of 0 isn’t valid, cids begin at 1. But of course it can end in 100. Since it’s a packed binary representation, it’s probably some other number leading to two zeroes at the end though.

As for BSSIDs: A lot of them are based on the mac address of the underlying wifi router. These are assigned statically by the manufacturer and unique per device. So you’d end up with the same networks always going to be problematic. Otherwise the available numbers should be evenly assigned.

But BSSIDs can also be generated adhoc using a specific prefix instead of the vendor prefix. Those would end up with a random number and you’d expect to see the 1 out of 256 percentage.

**Comment by jwhitlock** [comment]
After thinking about it, this issue should only cause problems in production. 

The bug is in the algorithm determining if a location query contains new station or ones that haven't been confirmed today. If any of the IDs trigger the bug, the whole location query is passed on as a report for further processing. The submit API always creates a report.

Currently, production is dominated by location queries, and would be impacted by this bug. Staging is only submit queries, being sent as an export from production.

Some CIDs should trigger the bug (``mod(cid, 256) == 0``), but WiFi observations are 30x cell station observations, so can be ignored for estimating impact. Bluetooth observations are even smaller, and the tasks are having no issues keeping up.
